"""Add location_id to job_seeker_profiles

Revision ID: 0689aa7c8796
Revises: c8932a40e642
Create Date: 2025-08-13 12:02:06.703160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0689aa7c8796'
down_revision: Union[str, None] = 'c8932a40e642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_seeker_profiles', 'locations', ['location_id'], ['id'])
    op.drop_column('job_seeker_profiles', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('location', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'job_seeker_profiles', type_='foreignkey')
    op.drop_column('job_seeker_profiles', 'location_id')
    # ### end Alembic commands ###
