"""Add UploadedCV model

Revision ID: 084eb1692c06
Revises: 6fd35e34c1f0
Create Date: 2025-08-13 17:34:23.542800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084eb1692c06'
down_revision: Union[str, None] = '6fd35e34c1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('cv_filename', sa.String(length=255), nullable=False),
    sa.Column('desired_position', sa.String(length=255), nullable=True),
    sa.Column('desired_level', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_cvs_id'), 'uploaded_cvs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_cvs_id'), table_name='uploaded_cvs')
    op.drop_table('uploaded_cvs')
    # ### end Alembic commands ###
