"""Remove ai_category_map table

Revision ID: 0eea9bdaa504
Revises: b0b61e169bfd
Create Date: 2025-08-17 11:58:44.243385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0eea9bdaa504'
down_revision: Union[str, None] = 'b0b61e169bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_category_map_general_term'), table_name='ai_category_map')
    op.drop_index(op.f('ix_ai_category_map_id'), table_name='ai_category_map')
    op.drop_index(op.f('ix_ai_category_map_specific_title'), table_name='ai_category_map')
    op.drop_table('ai_category_map')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_category_map',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('general_term', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('specific_title', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_ai_category_map_specific_title'), 'ai_category_map', ['specific_title'], unique=False)
    op.create_index(op.f('ix_ai_category_map_id'), 'ai_category_map', ['id'], unique=False)
    op.create_index(op.f('ix_ai_category_map_general_term'), 'ai_category_map', ['general_term'], unique=False)
    # ### end Alembic commands ###
