"""Add location_id to job_posts table

Revision ID: 0f08ab27eea2
Revises: b76401ad2834
Create Date: 2025-08-13 11:26:00.359544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f08ab27eea2'
down_revision: Union[str, None] = 'b76401ad2834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_posts', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.drop_column('job_posts', 'location_id')
    # ### end Alembic commands ###
