"""create jobpost table

Revision ID: 291a775cf062
Revises: 040530e2b4d0
Create Date: 2025-06-02 16:17:18.461749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291a775cf062'
down_revision: Union[str, None] = '040530e2b4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job_posts', 'users', ['employer_email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    # ### end Alembic commands ###
