"""create companyinfo table

Revision ID: 4d118177fca1
Revises: fcd382ac79c5
Create Date: 2025-07-28 17:57:38.433421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d118177fca1'
down_revision: Union[str, None] = 'fcd382ac79c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('cover_filename', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_info')
    # ### end Alembic commands ###
