"""create jobpost table

Revision ID: 54a57f0b9a7c
Revises: 291a775cf062
Create Date: 2025-06-02 16:33:42.197923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a57f0b9a7c'
down_revision: Union[str, None] = '291a775cf062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('company_intro', sa.Text(), nullable=True))
    op.add_column('job_posts', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('job_posts', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('job_posts', sa.Column('how_to_apply', sa.Text(), nullable=True))
    op.add_column('job_posts', sa.Column('logo_filename', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('job_posts_ibfk_1'), 'job_posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('job_posts_ibfk_1'), 'job_posts', 'users', ['employer_email'], ['email'])
    op.drop_column('job_posts', 'logo_filename')
    op.drop_column('job_posts', 'how_to_apply')
    op.drop_column('job_posts', 'benefits')
    op.drop_column('job_posts', 'requirements')
    op.drop_column('job_posts', 'company_intro')
    # ### end Alembic commands ###
