"""create application table

Revision ID: 80345abaf552
Revises: eed179a695dc
Create Date: 2025-06-02 19:20:08.020936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80345abaf552'
down_revision: Union[str, None] = 'eed179a695dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('experience_places', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('certificates', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('cv_filename', sa.String(length=255), nullable=True))
    op.alter_column('applications', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True)
    op.alter_column('applications', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('applications', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'preferred_location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('applications', 'english_certificate')
    op.drop_column('applications', 'experience_companies')
    op.drop_column('applications', 'resume_filename')
    op.drop_column('applications', 'confirm_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('confirm_email', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('applications', sa.Column('resume_filename', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('applications', sa.Column('experience_companies', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('applications', sa.Column('english_certificate', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('applications', 'preferred_location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'phone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('applications', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'gender',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('applications', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('applications', 'cv_filename')
    op.drop_column('applications', 'certificates')
    op.drop_column('applications', 'experience_places')
    # ### end Alembic commands ###
