"""Remove main cv_filename from profile, use UploadedCV instead

Revision ID: 8a49d138397e
Revises: 084eb1692c06
Create Date: 2025-08-13 17:43:23.976302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a49d138397e'
down_revision: Union[str, None] = '084eb1692c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_seeker_profiles', 'cv_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker_profiles', sa.Column('cv_filename', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
