"""thay đổi mô tả, ví dụ: replace industry with career_id

Revision ID: a82d0b05b796
Revises: bf61b1f5abe0
Create Date: 2025-08-03 06:15:32.144684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82d0b05b796'
down_revision: Union[str, None] = 'bf61b1f5abe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
