"""Add ai_category_map table for AI knowledge

Revision ID: b0b61e169bfd
Revises: cd17a47e86ab
Create Date: 2025-08-17 11:21:01.914988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b61e169bfd'
down_revision: Union[str, None] = 'cd17a47e86ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_category_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('general_term', sa.String(length=255), nullable=False),
    sa.Column('specific_title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_category_map_general_term'), 'ai_category_map', ['general_term'], unique=False)
    op.create_index(op.f('ix_ai_category_map_id'), 'ai_category_map', ['id'], unique=False)
    op.create_index(op.f('ix_ai_category_map_specific_title'), 'ai_category_map', ['specific_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_category_map_specific_title'), table_name='ai_category_map')
    op.drop_index(op.f('ix_ai_category_map_id'), table_name='ai_category_map')
    op.drop_index(op.f('ix_ai_category_map_general_term'), table_name='ai_category_map')
    op.drop_table('ai_category_map')
    # ### end Alembic commands ###
