"""replace industry with career_id in company_info

Revision ID: bf61b1f5abe0
Revises: ddfa833d8569
Create Date: 2025-08-03 06:12:01.748094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf61b1f5abe0'
down_revision: Union[str, None] = 'ddfa833d8569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_info', sa.Column('career_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_info', 'careers', ['career_id'], ['id'])
    op.drop_column('company_info', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_info', sa.Column('industry', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'company_info', type_='foreignkey')
    op.drop_column('company_info', 'career_id')
    # ### end Alembic commands ###
