"""Add thumbnail_filename to UploadedCV model

Revision ID: c644aa97ce6c
Revises: 89f79bdf247e
Create Date: 2025-08-13 18:17:33.972525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c644aa97ce6c'
down_revision: Union[str, None] = '89f79bdf247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_cvs', sa.Column('thumbnail_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_cvs', 'thumbnail_filename')
    # ### end Alembic commands ###
