"""Add location_id to company_info table

Revision ID: c8932a40e642
Revises: 0f08ab27eea2
Create Date: 2025-08-13 11:31:22.509679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8932a40e642'
down_revision: Union[str, None] = '0f08ab27eea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_info', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_info', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_info', type_='foreignkey')
    op.drop_column('company_info', 'location_id')
    # ### end Alembic commands ###
