"""create jobpost table

Revision ID: cbeb7fc44ed3
Revises: d61935e20fa2
Create Date: 2025-08-01 22:42:58.370777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbeb7fc44ed3'
down_revision: Union[str, None] = 'd61935e20fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company_info', ['employer_id'])
    op.drop_column('job_posts', 'logo_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('logo_filename', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'company_info', type_='unique')
    # ### end Alembic commands ###
