"""Add detailed models for job seeker profile

Revision ID: ceac30c55f9e
Revises: 0689aa7c8796
Create Date: 2025-08-13 14:05:51.870034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceac30c55f9e'
down_revision: Union[str, None] = '0689aa7c8796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('certificate_name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('degree_name', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_id'), 'educations', ['id'], unique=False)
    op.create_table('language_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_skills_id'), 'language_skills', ['id'], unique=False)
    op.create_table('technical_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_skills_id'), 'technical_skills', ['id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_id'), 'work_experiences', ['id'], unique=False)
    op.add_column('job_seeker_profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_seeker_profiles', 'address')
    op.drop_column('job_seeker_profiles', 'marital_status')
    op.drop_column('job_seeker_profiles', 'gender')
    op.drop_column('job_seeker_profiles', 'date_of_birth')
    op.drop_index(op.f('ix_work_experiences_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_technical_skills_id'), table_name='technical_skills')
    op.drop_table('technical_skills')
    op.drop_index(op.f('ix_language_skills_id'), table_name='language_skills')
    op.drop_table('language_skills')
    op.drop_index(op.f('ix_educations_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
