"""create jobpost table

Revision ID: d61935e20fa2
Revises: 4d118177fca1
Create Date: 2025-08-01 22:04:56.411790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61935e20fa2'
down_revision: Union[str, None] = '4d118177fca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_posts', 'users', ['employer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.drop_column('job_posts', 'employer_id')
    # ### end Alembic commands ###
