"""add career_id to job_posts and update relationships

Revision ID: ddfa833d8569
Revises: db32d068a18b
Create Date: 2025-08-03 05:59:54.468471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfa833d8569'
down_revision: Union[str, None] = 'db32d068a18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('career_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_posts', 'careers', ['career_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_posts', type_='foreignkey')
    op.drop_column('job_posts', 'career_id')
    # ### end Alembic commands ###
