"""Add JobSeekerProfile table and relationship to User

Revision ID: edbc0154a144
Revises: d8e749317062
Create Date: 2025-08-03 19:49:54.282916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbc0154a144'
down_revision: Union[str, None] = 'd8e749317062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_seeker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desired_position', sa.String(length=255), nullable=True),
    sa.Column('desired_level', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('workplace_type', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('cv_filename', sa.String(length=255), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_job_seeker_profiles_id'), 'job_seeker_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_seeker_profiles_id'), table_name='job_seeker_profiles')
    op.drop_table('job_seeker_profiles')
    # ### end Alembic commands ###
