"""create application table

Revision ID: eed179a695dc
Revises: 4fd8bb4e806c
Create Date: 2025-06-02 19:17:13.018534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eed179a695dc'
down_revision: Union[str, None] = '4fd8bb4e806c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('applications', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('confirm_email', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('applications', sa.Column('birth_year', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('preferred_location', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('experience_fields', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('experience_companies', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('english_certificate', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('applications_ibfk_3'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_ibfk_1'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_ibfk_2'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'job_posts', ['job_id'], ['id'])
    op.drop_column('applications', 'match_score')
    op.drop_column('applications', 'user_id')
    op.drop_column('applications', 'resume_text')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('resume_text', mysql.TEXT(), nullable=True))
    op.add_column('applications', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('match_score', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_ibfk_2'), 'applications', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(op.f('applications_ibfk_1'), 'applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('applications_ibfk_3'), 'applications', 'users', ['user_id'], ['id'])
    op.drop_column('applications', 'resume_filename')
    op.drop_column('applications', 'cover_letter')
    op.drop_column('applications', 'english_certificate')
    op.drop_column('applications', 'experience_companies')
    op.drop_column('applications', 'experience_fields')
    op.drop_column('applications', 'preferred_location')
    op.drop_column('applications', 'birth_year')
    op.drop_column('applications', 'phone')
    op.drop_column('applications', 'confirm_email')
    op.drop_column('applications', 'email')
    op.drop_column('applications', 'gender')
    op.drop_column('applications', 'full_name')
    # ### end Alembic commands ###
