"""add status to job_posts

Revision ID: fcd382ac79c5
Revises: aa41497a7b67
Create Date: 2025-07-09 02:45:17.641595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fcd382ac79c5'
down_revision: Union[str, None] = 'aa41497a7b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('job_posts', 'status')
    # ### end Alembic commands ###
